export const enum ApiUrls {
    users = 'users',
    auth = 'auth',
    login = 'auth/login',
    task = 'task',
    taskCategory = 'task/category',
    taskPDF = 'task/pdf',
    userconfig = 'userconfig',
    budget = 'budget',
    budgetCategory = 'budget/category',
    budgetSpending = 'budget/spending',
    budgetCategoriesCost = 'statistics/budgetCategoriesCost',
    taskCategoriesDone = 'statistics/taskCategoriesDone',
    guestsSex = 'statistics/guestsSex',
    confirmedGuests = 'statistics/confirmedGuests',
    guests = 'guests',
    guestsGroup = 'guests/group',
}
