export const Categories = [
    'Planowanie',
    'Formalności',
    'Ceremonia',
    'Wesele',
    'Muzyka',
    'Zaproszenia',
    'Kwiaty i dekoracje',
    'Fotografia i wideo',
    'Transport',
    'Strój Panny Młodej',
    'Strój Pana Młodego',
    'Zdrowie i uroda',
    'Miesiąc miodowy',
];
